### PR TITLE
Multiple link fixes regarding the default branch (master to main)

### PR DESCRIPTION
**Pull request by mendel5**
While reading your website, e.g. [here](https://explained-from-first-principles.com/#what-software-do-you-use-to-create-the-graphics), I noticed an issue regarding a broken link to the Github `master` branch. Github shows the error message: "Branch not found, redirected to default branch.". I renamed all the links from `master` to `main` to fix this. I hope I got all of them.

### CODE REVIEW

**Comment by KasparEtter** [comment]
Great catch, I totally forgot about updating these links. Thanks for fixing them! I switched the branch only with the release of the article.

**Comment by mendel5** [comment]
Sure! Are you going to merge it?

**Comment by KasparEtter** [comment]
Yes. 🙂 Just didn't have the time today.

**Comment by mendel5** [comment]
Thanks for accepting my pull request! :rocket:

**Comment by KasparEtter** [comment]
Thank you for making the effort to fix my page! 🙂

**Pull request merged**
